#:schema ./schema.json

id = "apicat"
name = "ApiCat"
icon = "https://i.ibb.co/Fw8SqtB/apicat-500.png"
description = "ApiCat is an API development tool based on AI technology, which aims to help developers develop APIs more quickly and efficiently through automation and intelligence."

[source]
image = "natuo/apicat:v2.9.0"

[[ports]]
id = "web"
port = 8000
type = "HTTP"

[[volumes]]
id = "data"
dir = "/app"
